name: teenastro_app
description: TeenAstro telescope controller - replaces the SHC hardware controller
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/catalogs/
    - assets/data/
